#!/system/bin/sh
#
# Script to start "gtoolcmd" on the device, which has a very rudimentary
# shell.
#


base=/system
export CLASSPATH=$base/framework/gtoolCmd.jar
exec app_process $base/bin com.android.gtool.GtoolCommand "$@"